### ISSUE TITLE
Modify Vector3d

### ISSUE THREAD

**Issue by bbsy789** [walkandthinker/AsFem#52]
Compiler:MSVC;
OS:Windows 10;
Thanks for the issue raised by "Qingchen", and I am "Jie" in this QQ group(879908352). 
In the Vector3d Class which is declared in this path "include/Utils/Vector3d.h", the norm function throw a exception which is a Floating-point underflow. It may a undefine behavior due to use different compilers.
AsFEM is large .So I will only add some useful modify to Vector3d.

**Comment by yangbai90** [comment]
Hi Jie and Qingchen,

  Many thanks for the comments and feedback, now the devel branch is ready for your pull requests.

  Best,
  Yang

**Comment by yangbai90** [comment]
Thank you for the pull requests, the change has now been merged into the devel branch, and I'll close this issue.
