### ISSUE TITLE
Provide a Docker image where AsFem can be used

### ISSUE THREAD

**Issue by mscroggs** [walkandthinker/AsFem#62]
Installing the requirements of AsFem (Petsc, etc) can take a while. It would nice for new users is there was a Docker image or some other similar package that could be downloaded to use the library without having to build everything from source

**Comment by vijaysm** [comment]
While installing PETSc is less of a hassle in most systems, having a docker image will allow interested users to get started quickly. So I agree that this should be made available even if building the dependencies is straightforward. You may be able to take a stock Ubuntu image and install a [version of PETSc](https://packages.ubuntu.com/search?keywords=PETSc) directly to build AsFEM.

**Comment by schruste** [comment]
I agree with both, @mscroggs  and @vijaysm . Especially in view of a not too comfortable installation of AsFem and installation instructions that make several implicit assumptions (debian-based OS, etc..).

**Comment by yangbai90** [comment]
Dear all, thanks for the suggestion, I'm not familiar with docker, I'll take a look at it.

**Comment by vijaysm** [comment]
Please update if you have a Dockerfile available now.
