### ISSUE TITLE
Describe what is that makes the library "simple" in the JOSS paper

### ISSUE THREAD

**Issue by mscroggs** [walkandthinker/AsFem#63]
It's not fully clear to me which decisions have been made in this library to keep it "simple". Some questions you could consider to help clarify this:

- How big is the range of problems the library can solve?
- Which families of finite element basis functions does the library support? Is it lowest order Lagrange only?
- How is the user expected to interact with the library? Is this in a simpler way than other libraries?
- Which features have been left out of AsFem to keep it simple?

**Comment by schruste** [comment]
I would also add that it is really **necessary** to explain if and why the existing and powerful software frameworks such as fenics, mfem, ngsolve, etc... are not optimal here. Is it convenience, documentation, performance that AsFem can do better? To me it still seems that one of these modern FE frameworks with their very convenient python interfaces offer a higher degree of accessibility and flexibility without large (if any) performance penalties.

**Comment by yangbai90** [comment]
Dear @mscroggs and @schruste , thanks for the comments, I have added several explanation regarding your question and the comparison, please see the new pdf.
