### ISSUE TITLE
Devel branch,Clang compile warning:

### ISSUE THREAD

**Issue by bbsy789** [walkandthinker/AsFem#77]
`error: 'MeshGenerator::generateMesh' hides overloaded virtual functions [-Werror,-Woverloaded-virtual]`
`error: 'QPoint::generateQPoints' hides overloaded virtual functions [-Werror,-Woverloaded-virtual]`

this error occur in this classes.
`MeshGenerator`
`QPoint`

**Comment by yangbai90** [comment]
Dear @bbsy789 , thanks for pointing out this issue, some updates have been made to resolve this issue, please check the details here b2e36e8a3077811eeae8fbba0101effb4b36d268.

If it works in your test, you can close this issue.
