### ISSUE TITLE
Possible redundant code in ReadNLSolverBlock.cpp

### ISSUE THREAD

**Issue by Ran-Tu** [walkandthinker/AsFem#86]
Hi developer,

Could you please review the following lines? It seems that one of them is unnecessarily redundant.

https://github.com/MatMechLab/AsFem/blob/5b25ee305542ad77bd4a642c3f296c7d4dd42a12/src/InputSystem/ReadNLSolverBlock.cpp#L126-L148

Kind regards,
Ran

**Comment by yangbai90** [comment]
Hi @Ran-Tu , many thanks for highlighting this issue. I will address and resolve it in the upcoming commit.

**Comment by yangbai90** [comment]
Resolved in 00e181ea9cca5953e7def35a5b7b6abecca74562
